### ISSUE TITLE
Installing plugin results in error

### ISSUE THREAD

**Issue by ecodiv** [bojianzhu/qgis-fast-kernel-density-analysis#1]
Hi, I am trying to install the plugin, but this results in the error `ImportError: cannot import name 'GEOSException' from 'shapely.errors' (/usr/lib/python3/dist-packages/shapely/errors.py)`

**Comment by bojianzhu** [comment]
I'm sorry about that, maybe you need to update the shapely version, by
pip install --upgrade shapely

**Comment by ecodiv** [comment]
Thanks, that solved the above-mentioned problem. Now, however, I am getting the following error:

```
NameError: name 'nkdv_C_library' is not defined 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paulo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/__init__.py", line 23, in classFactory
    from .fast_density_analysis import FastDensityAnalysisPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paulo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/fast_density_analysis.py", line 25, in 
    from .fast_density_analysis_provider import FastDensityAnalysisProvider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paulo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/fast_density_analysis_provider.py", line 21, in 
    from .nkdvAlgorithm import NKDVAlgorithm
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paulo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/nkdvAlgorithm.py", line 25, in 
    from .nkdv import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paulo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/nkdv/__init__.py", line 1, in 
    from .nkdv import NKDV
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paulo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/nkdv/nkdv.py", line 1, in 
    from .compute_nkdv import compute_nkdv
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paulo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/nkdv/compute_nkdv.py", line 57, in 
    nkdv = nkdv_C_library.nkdv
NameError: name 'nkdv_C_library' is not defined
```
I am on Linux Ubuntu 22.04, QGIS version 3.32.2-Lima.

**Comment by bojianzhu** [comment]
That's a problem, maybe we haven't tested it fully in Linux.
I'm sorry about that. We will fix it as soon as possible.
We promise it can run correctly in Windows OS right now.

**Comment by vovchykbratyk** [comment]
Same issue as @ecodiv on Mac M1 (QGIS 3.36 installed via miniconda).

**Comment by odsemblante** [comment]
> That's a problem, maybe we haven't tested it fully in Linux.
> I'm sorry about that. We will fix it as soon as possible.
> We promise it can run correctly in Windows OS right now.

I'm on Windows, but I'm having the no geojson problem.

<img width="501" height="97" alt="Image" src="https://github.com/user-attachments/assets/e1decb78-9cdb-4f88-8cbe-ff278500d81b" />

Installed it as QGIS plugin.
