### ISSUE TITLE
Plugin activation fails with "No module named 'geojson'"

### ISSUE THREAD

**Issue by simbamangu** [bojianzhu/qgis-fast-kernel-density-analysis#2]
On installation / activation the plugin fails with "No module named 'geojson'". 

MacOS 13.5.2 / QGIS 3.23.x

<details>

```
Couldn't load plugin 'fast_kernel_density_analysis' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'geojson' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/__init__.py", line 23, in classFactory
    from .fast_density_analysis import FastDensityAnalysisPlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/fast_density_analysis.py", line 25, in 
    from .fast_density_analysis_provider import FastDensityAnalysisProvider
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/fast_density_analysis_provider.py", line 21, in 
    from .nkdvAlgorithm import NKDVAlgorithm
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/nkdvAlgorithm.py", line 20, in 
    from .utils.overpass import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/utils/overpass/__init__.py", line 14, in 
    from .api import API
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/fast_kernel_density_analysis/utils/overpass/api.py", line 9, in 
    import geojson
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'geojson'


Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.32.3-Lima Lima, 67d46100b5b 

Python Path:
/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Users/simbamangu/Library/Application Support/QGIS/QGIS3/profiles/default/python
.
```

</details>

**Comment by NyakudyaA** [comment]
You need to install the geojson using pip

```
pip install --target /Applications/QGIS.app/Contents/Resources/python/site-packages/ geojson
```
